name: Traducir HTML

on:
  push:
    paths:
      - 'ciclos/diw/u01_es.html'
      - 'ciclos/dwec/u01_es.html'
      - 'ciclos/ssii/u01_es.html'

permissions:
  contents: write

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          pip install deep-translator beautifulsoup4

      - name: Traducir archivos modificados
        run: python traducir.py

      - name: Guardar cambios en GitHub
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ciclos/diw/u01_en.html ciclos/dwec/u01_en.html ciclos/ssii/u01_en.html
          git diff --staged --quiet || (git commit -m "Traducción automática de unidades HTML" && git push)